version: '3.7'

services:
# create first react app
  # docker-compose run frontend npx create-react-app app
#  frontend:
#    image: node:16-alpine
#    volumes:
#      - ./app:/app

  frontend-react:
    build:
      context: docker/node
    container_name: frontend-react
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn start"
    tty: true
